
### mobile_price_classification




In [2]:
# 2️⃣ Load Dataset (from CSV)
df = pd.read_csv('/content/mobile_price_classification.csv')

# Separate features (X) and target (y)
X = df.drop('price_range', axis=1).values
y = df['price_range'].values

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

Shape of X: (2000, 20)
Shape of y: (2000,)


In [3]:
# 3️⃣ One-Hot Encode Target
# There are 4 classes (0, 1, 2, 3) in 'price_range'
y = to_categorical(y, num_classes=4)

print(f"Shape of y after one-hot encoding: {y.shape}")

Shape of y after one-hot encoding: (2000, 4)


In [4]:
# 4️⃣ Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")

Shape of X_train: (1600, 20)
Shape of X_test: (400, 20)


In [5]:
# 5️⃣ Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Features scaled.")

Features scaled.


In [6]:
# 6️⃣ Build ANN Model
# Input shape is 20 (number of features), output is 4 (number of classes)
model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)), # Dynamic input shape
    Dense(8, activation='relu'),
    Dense(4, activation='softmax') # 4 classes for multiclass classification
])

# 7️⃣ Compile Model
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 16)             │           336 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 4)              │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 508 (1.98 KB)

 Trainable params: 508 (1.98 KB)

 Non-trainable params: 0 (0.00 B)

In [7]:
# 8️⃣ Train Model
history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=32, # Adjusted batch size for larger dataset
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.2374 - loss: 1.7498 - val_accuracy: 0.2656 - val_loss: 1.5529
Epoch 2/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.2453 - loss: 1.5164 - val_accuracy: 0.2656 - val_loss: 1.4572
Epoch 3/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2852 - loss: 1.4289 - val_accuracy: 0.2906 - val_loss: 1.4203
Epoch 4/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3377 - loss: 1.3656 - val_accuracy: 0.2844 - val_loss: 1.3945
Epoch 5/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3624 - loss: 1.3416 - val_accuracy: 0.3031 - val_loss: 1.3643
Epoch 6/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3843 - loss: 1.3141 - val_accuracy: 0.3562 - val_loss: 1.3256
Epoch 7/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4415 - loss: 1.2565 - val_accuracy: 0.3688 - val_loss: 1.2711
Epoch 8/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4673 - loss: 1.2028 - val_accuracy: 0.4219 - v

In [8]:
# 9️⃣ Evaluate Model
loss, accuracy = model.evaluate(X_test, y_test)
print("\nTest Loss:", loss)
print("Test Accuracy:", accuracy)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9307 - loss: 0.1631  

Test Loss: 0.17496581375598907
Test Accuracy: 0.9275000095367432


In [9]:
# 🔟 Predictions
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

print("\nConfusion Matrix:\n", confusion_matrix(y_true, y_pred_classes))
print("\nClassification Report:\n", classification_report(y_true, y_pred_classes))

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 

Confusion Matrix:
 [[102   3   0   0]
 [  3  86   2   0]
 [  0   3  81   8]
 [  0   0  10 102]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97       105
           1       0.93      0.95      0.94        91
           2       0.87      0.88      0.88        92
           3       0.93      0.91      0.92       112

    accuracy                           0.93       400
   macro avg       0.93      0.93      0.93       400
weighted avg       0.93      0.93      0.93       400



In [10]:
!pip install keras-tuner #not inbuilt ( so we have to install)


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.8 MB/s eta 0:00:00


# Hyperparameter Tuning on Mobile Price Classification Data using Keras Tuner

In [11]:
# 1️⃣ Import Libraries
import numpy as np
import pandas as pd
import tensorflow as tf
import keras_tuner as kt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report

In [12]:
# 2️⃣ Load Dataset
df = pd.read_csv('/content/mobile_price_classification.csv')

# Separate features (X) and target (y)
X = df.drop('price_range', axis=1).values
y = df['price_range'].values

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

Shape of X: (2000, 20)
Shape of y: (2000,)


In [13]:
# 3️⃣ One-Hot Encode Target
# There are 4 classes (0, 1, 2, 3) in 'price_range'
y = to_categorical(y, num_classes=4)

print(f"Shape of y after one-hot encoding: {y.shape}")

Shape of y after one-hot encoding: (2000, 4)


In [14]:
# 4️⃣ Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")

Shape of X_train: (1600, 20)
Shape of X_test: (400, 20)


In [15]:
# 5️⃣ Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Features scaled.")

Features scaled.


In [16]:
# 6️⃣ Build Model Function for Tuner
def build_model(hp):
    model = Sequential()

    # Tune number of neurons for the first hidden layer
    model.add(Dense(
        units=hp.Int('units_1', min_value=8, max_value=64, step=8),
        activation='relu',
        input_shape=(X_train.shape[1],) # Adjusted for 20 features
    ))

    # Tune number of neurons for the second hidden layer
    model.add(Dense(
        units=hp.Int('units_2', min_value=8, max_value=64, step=8),
        activation='relu'
    ))

    # Tune dropout rate
    model.add(Dropout(
        rate=hp.Choice('dropout_rate', values=[0.2, 0.3, 0.4])
    ))

    model.add(Dense(4, activation='softmax')) # Adjusted for 4 classes

    # Tune learning rate for the Adam optimizer
    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate=hp.Choice('learning_rate', values=[0.01, 0.001, 0.0001])
        ),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

In [17]:
# 7️⃣ Initialize Tuner
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=10,
    directory='mobile_price_tuning',
    project_name='mobile_price_ann'
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
# 8️⃣ Search Best Hyperparameters
tuner.search(
    X_train, y_train,
    epochs=50,
    validation_split=0.2,
    batch_size=32, # Adjusted batch size for larger dataset
    verbose=1
)

Trial 10 Complete [00h 00m 12s]
val_accuracy: 0.621874988079071

Best val_accuracy So Far: 0.9437500238418579
Total elapsed time: 00h 01m 59s


In [19]:
# 9️⃣ Get Best Model
best_model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 14 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [20]:
# 🔟 Evaluate on Test Set
loss, accuracy = best_model.evaluate(X_test, y_test)
print("\nBest Model Test Accuracy:", accuracy)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9189 - loss: 0.1898  

Best Model Test Accuracy: 0.9175000190734863


In [21]:
# 1️⃣1️⃣ Show Best Hyperparameters
best_hp = tuner.get_best_hyperparameters(1)[0]
print("\nBest Hyperparameters:")
print("Units Layer 1:", best_hp.get('units_1'))
print("Units Layer 2:", best_hp.get('units_2'))
print("Dropout Rate:", best_hp.get('dropout_rate'))
print("Learning Rate:", best_hp.get('learning_rate'))


Best Hyperparameters:
Units Layer 1: 8
Units Layer 2: 64
Dropout Rate: 0.2
Learning Rate: 0.01


In [22]:
# 1️⃣2️⃣ Classification Report
y_pred = np.argmax(best_model.predict(X_test), axis=1)
y_true = np.argmax(y_test, axis=1)

print("\nClassification Report:\n")
print(classification_report(y_true, y_pred))

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

Classification Report:

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       105
           1       0.91      0.92      0.92        91
           2       0.83      0.92      0.87        92
           3       0.97      0.87      0.92       112

    accuracy                           0.92       400
   macro avg       0.92      0.92      0.92       400
weighted avg       0.92      0.92      0.92       400

